{% set version = "1.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modeldata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modeldata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modeldata/modeldata_{{ version }}.tar.gz
  sha256: 9561f515b3d61e6c6faee5b7554ce25ec117b65970a15b5f8e505165d0434d99

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-dplyr
    - r-purrr
    - r-rlang
    - r-tibble
  run:
    - r-base
    - r-mass
    - r-dplyr
    - r-purrr
    - r-rlang
    - r-tibble

test:
  commands:
    - $R -e "library('modeldata')"           # [not win]
    - "\"%R%\" -e \"library('modeldata')\""  # [win]

about:
  home: https://github.com/tidymodels/modeldata
  license: MIT
  summary: Data sets used for demonstrating or testing model-related packages are contained in this package.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: modeldata
# Title: Data Sets Used Useful for Modeling Packages
# Version: 0.0.1
# Authors@R: c( person(given = "Max", family = "Kuhn", email = "max@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph"))
# Description: Data sets used for demonstrating or testing model-related packages are contained in this package.
# Depends: R (>= 2.10)
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: false
# RoxygenNote: 7.0.1.9000
# URL: https://github.com/tidymodels/modeldata
# NeedsCompilation: no
# Packaged: 2019-11-29 20:50:24 UTC; maxkuhn
# Author: Max Kuhn [aut, cre], RStudio [cph]
# Maintainer: Max Kuhn <max@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-12-06 21:20:06 UTC
